version: '3.3'

services:
  db:
    image: 10.50.80.56:5005/ampath_mysql:5.7
    secrets:
      - etl_password
      - etl_user
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: dev
    volumes:
      - /home/achachiez/Code/Docker/mysql-conf:/etc/mysql/conf.d
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/achachiez/Code/SQL/etl:/etl
      - type: bind
        source: /var/lib/mysql
        target: /var/lib/mysql
secrets:
  etl_password:
    external: true
  etl_user:
    external: true